query GET_SUBMISSION($assignmentId: uuid!, $studentId: String!) {
  submission: submissions(where: {assignment_id: {_eq:$assignmentId}, student: {username: {_eq: $studentId}}}) {
    content
    assignment {
      id
      title
    }
    student{
      username
      fullname
      profilePicture: profile_picture
    }
    updatedAt: updated_at
  }
}
