mutation UPDATE_RESOURCE(
  $id: uuid!
  $title: String!
  $content: String!
  $published: Boolean
) {
  resource: update_resources_by_pk(
    pk_columns: { id: $id }
    _set: {
      content: $content
      title: $title
      published: $published
    }
  ) {
    id
    published
  }
}
